### ISSUE TITLE
Make Instructions Even Clearer

### ISSUE THREAD

**Issue by rfdevere** [GlobalCyberAlliance/GCADMARCRiskScanner#2]
Great tool, simple and functional. Could we ask the install instructions be updated to incorporate clearer instructions for people unfamiliar with Go.

Install Go on Windows, MacOS and Linux following the instructions here: https://golang.org/doc/install#install

Setting a Go path, Go needs a clear build path to work. You can define this in several ways as documented here: https://github.com/golang/go/wiki/SettingGOPATH

**Comment by sajeevsahadev** [comment]
How to build and run this application. After setup the GOPATH, what are the steps to taken? Any documentation is available for this?

**Comment by 0219dives** [comment]
How do you run this on bulk domains?

**Comment by rfdevere** [comment]
TBH I gave up, scripted in in bash to make a new call per line. Hope that helps.

**Comment by 0219dives** [comment]
Exactly what I've done tbh, however I've got 375 domains to check for each record type so that should be fun haha. Thanks for your help!

**Comment by rfdevere** [comment]
Get all your domains in column B of a spreadsheet, add the command syntax in column A and drag down to duplicate. In Column C add in a ‘ >>output.txt’.

Copy all back to a quick and dirty bash script.

**Comment by 0219dives** [comment]
Nice one thanks! worked perfect! :)

**Comment by Wolveix** [comment]
Hey guys, sorry that this issue went unanswered for a long time. I've just updated the repo's README to be more informative, and have fixed a big with the `bulk` command which prevented it from working when you tried using it like this:

```
drs bulk domain1.tld domain2.tld domain3.tld
```

Additionally, pre-compiled binaries can now be found under [releases](https://github.com/GlobalCyberAlliance/GCADMARCRiskScanner/releases).

**Comment by OrlandoMD** [comment]
@wolveix Wonderful - this project has come along way, very useful evaluating and analyzing many  domains!  I have a tabulated truth table to the right of industry results provided by this tool in CSV form to help periodically gauge status, parse and prioritize our direct shares with members - work well!
Orlando E-ISAC
